"""Templ build rules for generating Go code from .templ files."""

load("@io_bazel_rules_go//go:def.bzl", "go_library")


def templ_library(name, srcs, importpath, deps = [], templ_binary = None, templ_go_deps = None, visibility = ["//visibility:public"]):
    """Generate Go code from templ templates and expose it as a go_library.

    Args:
        name: Name of the generated go_library target.
        srcs: List of .templ source files.
        importpath: Go import path for the generated library.
        deps: Additional direct Go dependencies used by the templates.
        templ_binary: Label of the hermetic templ binary. Defaults to @templ//:bin.
        templ_go_deps: Go deps for templ runtime. Defaults to @com_github_a_h_templ, generated by the extension.
        visibility: Visibility for the generated go_library.
    """
    if templ_binary == None:
        templ_binary = "@templ//:bin"
    if templ_go_deps == None:
        templ_go_deps = [
            "@com_github_a_h_templ//:templ",
            "@com_github_a_h_templ//runtime",
        ]

    generated_go_files = []

    for src in srcs:
        if not src.endswith(".templ"):
            fail("templ_library srcs must end with .templ: {}".format(src))
        basename = src[:-len(".templ")]
        generated_filename = "{}_templ.go".format(basename)
        genrule_name = "{}_templ_gen".format(basename.replace("/", "_"))

        native.genrule(
            name = genrule_name,
            srcs = [src],
            outs = [generated_filename],
            cmd = """
                src_path=$(SRCS)
                src_dir=$${src_path%%/*}
                src_file=$${src_path##*/}
                templ_bin=$(location %s)
                cd "$$src_dir" && \
                "$$OLDPWD/$$templ_bin" generate -f "$$src_file" -include-version=false -log-level=error && \
                mv "$${src_file%%.templ}_templ.go" "$$OLDPWD/$(@D)"
            """ % templ_binary,
            tools = [templ_binary, "//:go.mod"],
            visibility = ["//visibility:private"],
        )

        generated_go_files.append(generated_filename)

    go_library(
        name = name,
        srcs = generated_go_files,
        importpath = importpath,
        deps = deps + templ_go_deps,
        visibility = visibility,
    )
