"""Repository rules for hermetic templ binaries."""

load("@bazel_gazelle//:deps.bzl", "go_repository")
load("//templ/private:versions.bzl", "PLATFORMS", "TEMPL_VERSIONS")

_DOC = "Fetch a hermetic templ binary from an upstream release"


def _host_platform(repository_ctx):
    os_name = repository_ctx.os.name.lower()
    arch = repository_ctx.os.arch.lower()

    if arch in ["x86_64", "amd64"]:
        arch = "amd64"
    elif arch in ["aarch64", "arm64"]:
        arch = "arm64"
    else:
        fail("Unsupported host architecture for templ: {}".format(repository_ctx.os.arch))

    if os_name.startswith("linux"):
        os_key = "linux"
    elif os_name.startswith("mac os") or os_name.startswith("darwin"):
        os_key = "darwin"
    else:
        fail("Unsupported host OS for templ: {}".format(repository_ctx.os.name))

    platform = "{}_{}".format(os_key, arch)
    if platform not in PLATFORMS:
        fail("Unsupported host platform for templ: {}".format(platform))
    return platform


def _sha256_for(repository_ctx, platform):
    if platform in repository_ctx.attr.sha256s:
        return repository_ctx.attr.sha256s[platform]

    version = repository_ctx.attr.templ_version
    if version in TEMPL_VERSIONS and platform in TEMPL_VERSIONS[version]:
        return TEMPL_VERSIONS[version][platform]

    fail("No sha256 known for templ version {} on platform {}. Pass sha256s = {{\"{}\": \"...\"}} to the extension tag.".format(version, platform, platform))


def _templ_repository_impl(repository_ctx):
    platform = repository_ctx.attr.platform
    if platform == "auto":
        platform = _host_platform(repository_ctx)

    meta = PLATFORMS[platform]
    version = repository_ctx.attr.templ_version
    url = "https://github.com/a-h/templ/releases/download/v{version}/templ_{os}_{arch}.tar.gz".format(
        version = version,
        os = meta.release_os,
        arch = meta.release_arch,
    )

    repository_ctx.download_and_extract(
        url = url,
        sha256 = _sha256_for(repository_ctx, platform),
    )

    repository_ctx.file("BUILD.bazel", """# Generated by rules_templ//templ:repositories.bzl
package(default_visibility = [\"//visibility:public\"])

load(\"@rules_templ//templ:tool.bzl\", \"templ_binary\")

templ_binary(
    name = \"bin\",
    binary = \"templ\",
)
""")


templ_repository = repository_rule(
    implementation = _templ_repository_impl,
    doc = _DOC,
    attrs = {
        "templ_version": attr.string(mandatory = True),
        "platform": attr.string(default = "auto", values = ["auto"] + PLATFORMS.keys()),
        "sha256s": attr.string_dict(default = {}),
    },
)


def templ_register_tool(name, go_repository_name = None, **kwargs):
    """Register a templ binary repository and its matching Go library repo.

    Args:
        name: Binary repository name to create, commonly "templ".
        go_repository_name: Go repository name. Defaults to Gazelle's conventional
            repository name "com_github_a_h_templ" for the default binary and
            "<name>_go" for named binaries.
        **kwargs: Passed to templ_repository; normally templ_version and optionally sha256s/platform.
    """
    templ_repository(name = name, **kwargs)

    if go_repository_name == None:
        go_repository_name = "com_github_a_h_templ" if name == "templ" else name + "_go"

    version = kwargs["templ_version"]
    if version not in TEMPL_VERSIONS or "go_sum" not in TEMPL_VERSIONS[version]:
        fail("No Go module sum known for templ version {}.".format(version))

    go_repository(
        name = go_repository_name,
        importpath = "github.com/a-h/templ",
        sum = TEMPL_VERSIONS[version]["go_sum"],
        version = "v" + version,
    )
